os:
  - linux
  - osx

language: csharp

services:
  - docker

env:
  - CONFIGURATION=Release

mono:
  - latest

sudo: required
dist: trusty

osx_image: xcode9.1

dotnet: 2.1.4

script:
  - dotnet restore IronPython.sln --packages ./packages
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]] ; then make ; fi
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]] ; then docker run -v /home/travis/build/IronLanguages/ironpython2:/home/travis/build/IronLanguages/ironpython2 mono:4.8 /bin/sh -c "apt-get update ; apt-get install make ; cd /home/travis/build/IronLanguages/ironpython2 && make test-all" ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] ; then make ; fi

notifications:
  email:
    recipients:
      - developers+int+211+854770831703316759@ironpython.groups.io
    on_success: always # default: change
    #on_failure: [always|never|change] # default: always
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/9fdb5c75f38c850816f8
