os:
  - linux
  - osx

language: csharp

env:
  - CONFIGURATION=Release

mono:
  - 4.8.0

solution: IronPython.sln

script:
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]] ; then sudo apt-get install -y binfmt-support libmono-system-windows-forms4.0-cil ; fi
  - make
  - make test-all

notifications:
  email:
    recipients:
      - developers+int+211+854770831703316759@ironpython.groups.io
    on_success: always # default: change
    #on_failure: [always|never|change] # default: always
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/9fdb5c75f38c850816f8
