os:
  - linux
  - osx

language: csharp

services:
  - docker

env:
  - CONFIGURATION=Release

mono:
  - latest
  - 4.8

matrix:
  exclude:
    - os: osx
      mono: latest
    - os: linux
      mono: 4.8

solution: IronPython.sln

script:
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]] ; then make ; fi
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]] ; then docker run -v /home/travis/build/IronLanguages/ironpython2:/home/travis/build/IronLanguages/ironpython2 mono:4.8 /bin/sh -c "apt-get update ; apt-get install make ; cd /home/travis/build/IronLanguages/ironpython2 && make test-all" ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] ; then docker run -v /Users/travis/build/IronLanguages/ironpython2:/home/travis/build/IronLanguages/ironpython2 mono:5.0 /bin/sh -c "cd /home/travis/build/IronLanguages/ironpython2 && make" ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] ; then make test-all ; fi

notifications:
  email:
    recipients:
      - developers+int+211+854770831703316759@ironpython.groups.io
    on_success: always # default: change
    #on_failure: [always|never|change] # default: always
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/9fdb5c75f38c850816f8
