os:
  - linux
  - osx

language: csharp

services:
  - docker

env:
  - CONFIGURATION=Release

mono:
  - latest
  - 4.8

matrix:
  exclude:
    - os: osx
      mono: latest
    - os: linux
      mono: 4.8

solution: IronPython.sln

script:
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]] ; then sudo apt-get install -y binfmt-support libmono-system-windows-forms4.0-cil ; fi
  - make
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]] ; then docker build -t mono-4.8 . ; fi
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]] ; then docker run mono-4.8 /bin/sh -c "make test-all" ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] ; then make test-all ; fi

notifications:
  email:
    recipients:
      - developers+int+211+854770831703316759@ironpython.groups.io
    on_success: always # default: change
    #on_failure: [always|never|change] # default: always
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/9fdb5c75f38c850816f8
